---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neuvector
  namespace: neuvector
spec:
  chart:
    spec:
      chart: core
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: neuvector-charts
        namespace: flux-system
      version: 2.4.1
  interval: 1m0s
  targetNamespace: neuvector
  values:
    containerd:
      enabled: true
