---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: perfectscale
  namespace: eks-anywhere
spec:
  chart:
    spec:
      chart: exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: perfectscale-charts
        namespace: flux-system
      version: v0.0.38
  interval: 1m0s
  targetNamespace: eks-anywhere
  values:
    secret:
      create:
        true
    settings:
      psUrl: "https://api.dev.perfectscale.click/psc-tenant-manager"
      uploadPolicyUrl: "https://api.dev.perfectscale.click/psc-presigned-policy"
  valuesFrom:
  - kind: Secret
    name: perfectscale-sm-secret
    valuesKey: clientId
    targetPath: secret.clientId
  - kind: Secret
    name: perfectscale-sm-secret
    valuesKey: clientSecret
    targetPath: secret.clientSecret   